_welcome:
    path:      /
    defaults:  { _controller: AppBundle:Blog:index, page: 1 }

_blog_index_paginated:
    path:   /page={page}
    defaults: { _controller: AppBundle:Blog:index, page: 1 }

_blog_single_post:
    path:   /slug/{slug}
    defaults: { _controller: AppBundle:Blog:findByTitle, slug: 1 }
    
_admin_vire:
    path:   /admin
    defaults: { _controller: AppBundle:Admin/Blog:admin, page: 1 }

_admin_index_paginated:
    path:   /admin/page={page}
    defaults: { _controller: AppBundle:Admin/Blog:admin, page: 1 }

_admin_delete_post:
    path:   /admin/delete={id}
    defaults: { _controller: AppBundle:Admin/Blog:delete, id: 1 }

_admin_add_post:
     path:   /admin/new
     defaults: { _controller: AppBundle:Admin/Blog:newPost}

_login_route:
    path:  /login
    defaults: { _controller: AppBundle:Security:login}

_login_check:
    path:  /login_check
    defaults: { _controller: AppBundle:Security:loginCheck}

_logout:
    path: /logout
